### ISSUE TITLE
Better comparison between libraries

### ISSUE THREAD

**Issue by tsantos84** [better-serializer/better-serializer#14]
Hi @Rastusik, nice to see that you, like me, didn't got comfortable with JMS' performance. I'm also writing a serializer library and the results are very promising as yours. The difference between our libraries is that I'm using generated hydrators to read and write data from objects to avoid any `guessing` in runtime like discovering property type, property accessors and mutators. I've started this project after making some benchmark with JMS and Symfony and realized that both has considerable overhead. You can check out the benchmark on https://github.com/tsantos84/serializer-benchmark. When I discovered `better-serializer` the first thing I've made was put the library in my benchmark tool and saw that it has a promising approach. However, in order to make a fair comparison with others libraries, would be nice if you implement common features like property grouping, circular reference handler, mapping of interface and abstract classes so we can compare orange with orange. The presence of those features is enough to add some overhead to your code base even they aren't enabled on a serialization processing and then you can have more accurate results.

**Comment by Rastusik** [comment]
Hi @tsantos84 ! Great that you see the space in improvement too! :) I'm not sure whether you've seen my approach, because I'm doing the same thing, your Hydrators are just named Processors in my code :) ... your benchmarks are quite interesting. Yes, I'll need to do some stuff, to be compatible with your feature set. This is kind of a problem right now, since I have other priorities, but I'll try some time. For a simplified comparison, maybe you could try to implement this sets of benchmarks: 
https://github.com/better-serializer/ivory-serializer-benchmark ... It should be quite straightforward. I can try as well when find some time :) .... there are two types of benchmarks - one is a simple custom thing, the other one uses phpbench

**Comment by Rastusik** [comment]
@tsantos84 check this benchmark with all the serializers, maybe this could be enough? https://github.com/php-serializers/ivory-serializer-benchmark/pull/17

**Comment by tsantos84** [comment]
yeah. I've also contributed to that tool. There is a thread explaining exactly whether all serializers should have the same feature or not and the conclusion is that they don't need to have the same capabilities, but a list of its features should be included in somewhere to help developers to choose the proper one.
